FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    musescore3 \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-docker.txt .
RUN pip install --no-cache-dir -r requirements-docker.txt
RUN pip install --no-cache-dir basic-pitch --no-deps

COPY api/requirements.txt api_requirements.txt
RUN pip install --no-cache-dir -r api_requirements.txt

COPY . .

COPY worker_start.sh .
RUN chmod +x worker_start.sh

CMD ["./worker_start.sh"]
